/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root.jsx'
import { Route as IndexRoute } from './routes/index.jsx'
import { Route as LoginRoute } from './routes/login.jsx'
import { Route as DashboardRoute } from './routes/dashboard.jsx'
import { Route as CatalogRoute } from './routes/products.jsx'
import { Route as CatalogProductManageRoute } from './routes/products.product.manage.jsx'

// Create/Update Routes

const IndexRouteUpdated = IndexRoute.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const LoginRouteUpdated = LoginRoute.update({
  path: '/login',
  getParentRoute: () => rootRoute,
})

const DashboardRouteUpdated = DashboardRoute.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
})

const CatalogRouteUpdated = CatalogRoute.update({
  path: '/products',
  getParentRoute: () => rootRoute,
})

const CatalogProductManageRouteUpdated = CatalogProductManageRoute.update({
  path: '/products/product/manage',
  getParentRoute: () => rootRoute,
})

// Populate the FileRoutesByPath interface

// declare module '@tanstack/react-router' {
//   interface FileRoutesByPath {
//     '/': {
//       id: '/'
//       path: '/'
//       fullPath: '/'
//       preLoaderRoute: typeof IndexRoute
//       parentRoute: typeof rootRoute
//     }
//     '/products': {
//       id: '/products'
//       path: '/products'
//       fullPath: '/products'
//       preLoaderRoute: typeof CatalogRoute
//       parentRoute: typeof rootRoute
//     }
//     '/products/product/manage': {
//       id: '/products/product/manage'
//       path: '/products/product/manage'
//       fullPath: '/products/product/manage'
//       preLoaderRoute: typeof CatalogProductManageRoute
//       parentRoute: typeof rootRoute
//     }
//     '/dashboard': {
//       id: '/dashboard'
//       path: '/dashboard'
//       fullPath: '/dashboard'
//       preLoaderRoute: typeof DashboardRoute
//       parentRoute: typeof rootRoute
//     }
//     '/login': {
//       id: '/login'
//       path: '/login'
//       fullPath: '/login'
//       preLoaderRoute: typeof LoginRoute
//       parentRoute: typeof rootRoute
//     }
//   }
// }

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute: IndexRouteUpdated,
  LoginRoute: LoginRouteUpdated,
  DashboardRoute: DashboardRouteUpdated,
  CatalogRoute: CatalogRouteUpdated,
  CatalogProductManageRoute: CatalogProductManageRouteUpdated,
})

/* prettier-ignore-end */
